USE [Library]
GO

DROP TABLE IF EXISTS AUTHOR_WORKS
GO

DROP TABLE IF EXISTS AUTHORS
GO

CREATE TABLE AUTHORS
(
	ID		INT IDENTITY (1, 1),
	[NAME]	NVARCHAR(50),

	CONSTRAINT PK_AUTHORS_ID PRIMARY KEY (ID)
)
GO

CREATE TABLE AUTHOR_WORKS
(
	ID			INT IDENTITY (1, 1),
	AUTHOR_ID	INT NOT NULL,
	[NAME]		NVARCHAR(50),

	CONSTRAINT PK_AUTHOR_WORKS_ID PRIMARY KEY (ID),
	CONSTRAINT FK_AUTHOR_WORKS_AUTHOR_ID FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID)
)
GO
