BEGIN TRANSACTION 
BEGIN TRY

	IF((SELECT COUNT(*) FROM dbo.AUTHOR_WORKS) <> 0)
	BEGIN
		DELETE FROM AUTHOR_WORKS
		DBCC CHECKIDENT ('AUTHOR_WORKS', RESEED, 0)
	END

	IF((SELECT COUNT(*) FROM dbo.AUTHORS) <> 0)
	BEGIN
		DELETE FROM AUTHORS
		DBCC CHECKIDENT ('AUTHORS', RESEED, 0)
	END

	COMMIT TRANSACTION

END TRY

BEGIN CATCH
	ROLLBACK TRANSACTION
	PRINT 'DELETING ALL RECORDS FAILED'
END CATCH
GO

BEGIN TRANSACTION
BEGIN TRY
	
	INSERT AUTHORS (NAME) VALUES ('Иван Вазов')
	INSERT AUTHORS (NAME) VALUES ('Христо Ботев')
	INSERT AUTHORS (NAME) VALUES ('Христо Смирненски')
	INSERT AUTHORS (NAME) VALUES ('Елин Пелин')
	INSERT AUTHORS (NAME) VALUES ('Пейо Яворов')
	INSERT AUTHORS (NAME) VALUES ('Никола Вапцаров')

	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION
	PRINT 'INSERTING INTO AUTHORS FAILED'
END CATCH

BEGIN TRANSACTION
BEGIN TRY
	
	INSERT AUTHOR_WORKS (AUTHOR_ID, NAME) VALUES (1, 'Една българка')
	INSERT AUTHOR_WORKS (AUTHOR_ID, NAME) VALUES (1, 'Апостола в премеждие')
	INSERT AUTHOR_WORKS (AUTHOR_ID, NAME) VALUES (2, 'На прощаване')
	INSERT AUTHOR_WORKS (AUTHOR_ID, NAME) VALUES (2, 'Майце си')
	INSERT AUTHOR_WORKS (AUTHOR_ID, NAME) VALUES (3, 'Огнен път')
	INSERT AUTHOR_WORKS (AUTHOR_ID, NAME) VALUES (3, 'През бурята')
	INSERT AUTHOR_WORKS (AUTHOR_ID, NAME) VALUES (4, 'Косачи')
	INSERT AUTHOR_WORKS (AUTHOR_ID, NAME) VALUES (4, 'Гераците')
	INSERT AUTHOR_WORKS (AUTHOR_ID, NAME) VALUES (5, 'Две души')
	INSERT AUTHOR_WORKS (AUTHOR_ID, NAME) VALUES (5, 'Ще бъдеш в бяло')
	INSERT AUTHOR_WORKS (AUTHOR_ID, NAME) VALUES (6, 'Песен за човека')
	INSERT AUTHOR_WORKS (AUTHOR_ID, NAME) VALUES (6, 'Пролет')

	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION
	PRINT 'INSERTING INTO AUTHORS FAILED'
END CATCH